service: go-mysql-hello-world

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  memorySize: 128

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: post
